### ISSUE TITLE
有左右滑的區塊都是空白的

### ISSUE THREAD

**Issue by hereismglee** [g0v-news/gov-hackers#1]
我的手機(htc) 在臺灣篇跟外國篇的左右劃區域，是空白的，看不到各文章

**Comment by yutin1987** [comment]
應該是 http 與 https 的問題, 剛剛 fix 了!! 試試看

**Comment by hereismglee** [comment]
還是不行耶 哭哭 已經是 https 了

**Comment by yutin1987** [comment]
QQ... 明天跟你借手機試試

**Comment by chihhhhhao** [comment]
發現跟我在 #6 裡面描述的大概是一樣的現象？自主 debug 中。

**Comment by hereismglee** [comment]
chihao ++

測試機種
Samsung galaxy tab, andriod 4.2.2, chrome, 8" 1280 x 800
HTC ONE M7, andriod 4.4.2, chrome, 4.7" 1920×1080
iPad mini, iOS 10.2.1, chrome & safari, 2048 x 1536

測試數台後，有一樣的問題：
1) loading 花 1~2 分鐘才出現
2) 所有左右滑的 (國內篇、國外篇、唐鳳vs公務員、hacker分享文) 都是空白，卡在左邊螢幕外，只露出一點點，但怎麼用手勢往右，都無法把畫面拉出來。 
3) 空白區的最下面有 1,2,3,4.. 的列點

另外抱歉，我今天不會去 OCF

**Comment by chihhhhhao** [comment]
@hereismglee++ 如果可以的話，請補充說明瀏覽器名稱、版號、作業系統名稱、版號、device型號、螢幕大小。（可以編輯發言喔 🙂）

**Comment by yutin1987** [comment]
應該是 react-slick css 的 cdn 問題。 剛剛已經 fixed。再幫我驗證一下，如果沒 bug 了！請幫我 close 它 :)
