### ISSUE TITLE
4 個黑客進政府實錄，橫幅

### ISSUE THREAD

**Issue by aelcenganda** [g0v-news/gov-hackers#12]
在 iphone 5c 上會 kiang & Peggy 照片與標題重疊。
Peggy, TonyQ 的文字介紹與 quote 會重疊。

![17453661_120300002702359830_1223303310_o](https://cloud.githubusercontent.com/assets/9480974/24186731/8f38a1a8-0f14-11e7-87c3-ce41d8dcb558.jpg)

**Comment by yutin1987** [comment]
感謝!!! 320px 的手機字會太大 我晚一點統一縮小字級

**Comment by aelcenganda** [comment]
Desktop 版國內篇跑掉
![2017-03-22 17 40 04](https://cloud.githubusercontent.com/assets/9480974/24191403/b6c72c50-0f26-11e7-9b4c-e23b118e0a10.png)

**Comment by chihhhhhao** [comment]
已修正。
