### ISSUE TITLE
大事記錯字

### ISSUE THREAD

**Issue by hereismglee** [g0v-news/gov-hackers#2]
八仙塵"爆"

**Comment by chihhhhhao** [comment]
這個是從文案就錯了，新版的設計稿已經更正了 🙇

**Comment by hereismglee** [comment]
（其實最早的文案是我寫錯的XD）感謝 debug!

**Comment by yutin1987** [comment]
看能否幫我 直接修改 https://github.com/g0v-news/gov-hackers/blob/master/src/assets/content.js 這份文字檔 fix it 🙇

**Comment by hereismglee** [comment]
fixed and added some links (授權與協力刊登部分)
