### ISSUE TITLE
各個區塊的間距、空白、可否統一高度。

### ISSUE THREAD

**Issue by ttcat** [g0v-news/gov-hackers#21]
例如手機版

「④個黑客
進政府實錄
從中央部會到地方，當時被風光迎入政府的他們，是公關、救火隊，還是總教練？」

這個標題跟上下區塊的間距

與

「越洋專訪
找黑客與政府的
④種關係」

跟上下區塊的間距不同

**Comment by chihhhhhao** [comment]
已修正。

**Comment by ttcat** [comment]
++ 看到了！

漏了日本前面這段？
![img_1098](https://cloud.githubusercontent.com/assets/1935330/24323048/c3fe449a-11aa-11e7-9c2b-ebe154b17ce6.PNG)
