### ISSUE TITLE
網頁版國外篇主照片

### ISSUE THREAD

**Issue by hereismglee** [g0v-news/gov-hackers#23]
是否要跟國內篇的風格一致，放在主標題右側，上方與主標上方切齊？

![image](https://cloud.githubusercontent.com/assets/13115122/24201817/2382b3d0-0f4c-11e7-8f14-57cf14897afc.png)
![image](https://cloud.githubusercontent.com/assets/13115122/24201827/2b4429f0-0f4c-11e7-962e-fda0d46d52c0.png)

**Comment by yutin1987** [comment]
cc. @chihaoyo ? 我記得是刪掉這張圖 @@? 在 desktop

**Comment by chihhhhhao** [comment]
國外篇的cover photo只在mobile顯示，已修正。
