### ISSUE TITLE
可能錯別字

### ISSUE THREAD

**Issue by thewayiam** [g0v-news/gov-hackers#26]
[此篇](https://g0v.news/%E9%BB%91%E5%AE%A2%E5%85%AC%E5%8B%99%E5%93%A1-%E4%B8%AD-%E7%95%B6%E9%BB%91%E5%AE%A2%E6%9D%BE%E5%8F%AA%E7%95%99%E4%B8%8B%E4%B8%80%E6%97%A5%E6%BF%80%E6%83%85-ce93ad56a584#.sulreq9xa) 約前四分之一處

讓長期*更運*議題的相關非營利組織提出想法

![image](https://cloud.githubusercontent.com/assets/4479861/24208253/12f71e9a-0f5e-11e7-905c-730496434b28.png)

**Comment by yutin1987** [comment]
cc @aelcenganda

**Comment by hereismglee** [comment]
fixed
