### ISSUE TITLE
電腦前的黑客

### ISSUE THREAD

**Issue by hereismglee** [g0v-news/gov-hackers#4]
我看不到首頁圖的"電腦前的黑客" 只有一大片黑

Samsung galaxy tab�, andriod 4.2.2, chrome, 8" 1280 x 800
HTC ONE M7, andriod 4.4.2, chrome, 4.7" 1920×1080
iPad mini, iOS 10.2.1, chrome & safari, 2048 x 1536

**Comment by yutin1987** [comment]
fixed

**Comment by hereismglee** [comment]
ok 看到了!
