### ISSUE TITLE
橫向滑動區域與滑動手勢

### ISSUE THREAD

**Issue by chihhhhhao** [g0v-news/gov-hackers#6]
- 在橫向滑動區域，往左滑的時候只要一個不小心，就可以讓整頁往左捲動，在頁面右邊製造出一條空白。（Safari; iOS 10.0.1; iPhone 5; 320px*568px）

- 橫向滑動區域空白，往左滑會發現其實內容都藏在viewport左邊，每一格垂直排列。結束滑動手勢之後內容就消失了。（Safari; iOS 10.2.1; iPhone 6+; 414px*736px）

**Comment by chihhhhhao** [comment]
第二點：發現往左滑第一次內容會短暫出現，之後三次不會有東西，再下一次內容又會短暫出現，所以是滑四次會出現一次，跟區域裡面格子的數量吻合哦。

再來，在iPhone 6+上頁面loading time是1.3分鐘，最後發現是這個錯誤：

> [Error] Failed to load resource: 要求逾時。 (react-slick.css, line 0)

在iPhone 5上loading time是7秒，也沒有出現任何錯誤，所以強烈懷疑就是他造成橫向滑動失效。

**Comment by yutin1987** [comment]
react-slick css 問題 與 #1  的狀況ㄧ樣， 剛剛 fixed 。
如果依然有錯誤，再 commit 在 #1 下方 :)
